'''

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

'''

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        sHash = {}
        for char in s:
            sHash[char] = sHash.get(char, 0) + 1
        
        for char in t:
            if char not in sHash:
                return(char)
            
            sHash[char] = sHash[char]-1
            
        for char in sHash:
            if sHash[char] == -1:
                return(char)
